services:
  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:2000}
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:2000}
    depends_on:
      - backend
    extra_hosts:
      - "localhost:host-gateway"
    develop:
      watch:
        - path: ./frontend
          target: /app
          action: sync
        - path: ./frontend/package.json
          action: rebuild

  backend:
    build:
      context: ./backend
    ports:
      - "2000:2000"
    volumes:
      - /app/node_modules
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/kandypack
      - NODE_ENV=development
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
        restart: true
    develop:
      watch:
        - path: ./backend
          target: /app
          action: sync
        - path: ./backend/package.json
          action: rebuild
  db:
    build:
      context: ./db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kandypack
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init-scripts/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d kandypack"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  