/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Kandypack
 * Development documentation
 * OpenAPI spec version: 1.0.0
 */
export type GetIndex200One = {
	message: string;
	time: string;
};

export type GetIndex200Two = {
	message: string;
	time: string;
};

export type GetIndex200Three = {
	message: string;
	time: string;
};

export type getIndexResponse200ApplicationJson = {
	data: GetIndex200One;
	status: 200;
};

export type getIndexResponse200MultipartFormData = {
	data: GetIndex200Two;
	status: 200;
};

export type getIndexResponse200TextPlain = {
	data: GetIndex200Three;
	status: 200;
};

export type getIndexResponseComposite =
	| getIndexResponse200ApplicationJson
	| getIndexResponse200MultipartFormData
	| getIndexResponse200TextPlain;

export type getIndexResponse = getIndexResponseComposite & {
	headers: Headers;
};

export const getGetIndexUrl = () => {
	return `http://backend:2000/`;
};

export const getIndex = async (
	options?: RequestInit,
): Promise<getIndexResponse> => {
	const res = await fetch(getGetIndexUrl(), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();
	const data: getIndexResponse["data"] = body ? JSON.parse(body) : {};

	return { data, status: res.status, headers: res.headers } as getIndexResponse;
};
