/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Kandypack
 * Development documentation
 * OpenAPI spec version: 1.0.0
 */

import type { BodyType } from "./mutator";
import { customInstance } from "./mutator";
export type GetAuthValidate200One = {
	valid: boolean;
};

export type GetAuthValidate200Two = {
	valid: boolean;
};

export type GetAuthValidate200Three = {
	valid: boolean;
};

export type PostAuthSignUpBodyOne = {
	name: string;
	username: string;
	password: string;
};

export type PostAuthSignUpBodyTwo = {
	name: string;
	username: string;
	password: string;
};

export type PostAuthSignUpBodyThree = {
	name: string;
	username: string;
	password: string;
};

export type PostAuthSignUp200One = {
	username: string;
	role: string;
	token: string;
};

export type PostAuthSignUp200Two = {
	username: string;
	role: string;
	token: string;
};

export type PostAuthSignUp200Three = {
	username: string;
	role: string;
	token: string;
};

export type PostAuthSignUp400One = {
	message: string;
};

export type PostAuthSignUp400Two = {
	message: string;
};

export type PostAuthSignUp400Three = {
	message: string;
};

export type PostAuthSignUp500One = {
	message: string;
};

export type PostAuthSignUp500Two = {
	message: string;
};

export type PostAuthSignUp500Three = {
	message: string;
};

export type PostAuthSignInBodyOne = {
	username: string;
	password: string;
};

export type PostAuthSignInBodyTwo = {
	username: string;
	password: string;
};

export type PostAuthSignInBodyThree = {
	username: string;
	password: string;
};

export type PostAuthSignIn200One = {
	username: string;
	role: string;
	token: string;
};

export type PostAuthSignIn200Two = {
	username: string;
	role: string;
	token: string;
};

export type PostAuthSignIn200Three = {
	username: string;
	role: string;
	token: string;
};

export type PostAuthSignIn400One = {
	message: string;
};

export type PostAuthSignIn400Two = {
	message: string;
};

export type PostAuthSignIn400Three = {
	message: string;
};

export type GetIndex200One = {
	message: string;
	time: string;
};

export type GetIndex200Two = {
	message: string;
	time: string;
};

export type GetIndex200Three = {
	message: string;
	time: string;
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getAuthValidate = (
	options?: SecondParameter<typeof customInstance>,
) => {
	return customInstance<GetAuthValidate200One | Blob | GetAuthValidate200Three>(
		{ url: `http://localhost:2000/auth/validate`, method: "GET" },
		options,
	);
};

export const postAuthSignOut = (
	options?: SecondParameter<typeof customInstance>,
) => {
	return customInstance<null>(
		{ url: `http://localhost:2000/auth/sign-out`, method: "POST" },
		options,
	);
};

export const postAuthSignUp = (
	postAuthSignUpBody:
		| BodyType<
				PostAuthSignUpBodyOne | PostAuthSignUpBodyTwo | PostAuthSignUpBodyThree
		  >
		| PostAuthSignUpBodyTwo
		| PostAuthSignUpBodyThree,
	options?: SecondParameter<typeof customInstance>,
) => {
	return customInstance<PostAuthSignUp200One | Blob | PostAuthSignUp200Three>(
		{
			url: `http://localhost:2000/auth/sign-up`,
			method: "POST",
			data: postAuthSignUpBody,
		},
		options,
	);
};

export const postAuthSignIn = (
	postAuthSignInBody:
		| BodyType<
				PostAuthSignInBodyOne | PostAuthSignInBodyTwo | PostAuthSignInBodyThree
		  >
		| PostAuthSignInBodyTwo
		| PostAuthSignInBodyThree,
	options?: SecondParameter<typeof customInstance>,
) => {
	return customInstance<PostAuthSignIn200One | Blob | PostAuthSignIn200Three>(
		{
			url: `http://localhost:2000/auth/sign-in`,
			method: "POST",
			data: postAuthSignInBody,
		},
		options,
	);
};

export const getIndex = (options?: SecondParameter<typeof customInstance>) => {
	return customInstance<GetIndex200One | Blob | GetIndex200Three>(
		{ url: `http://localhost:2000/`, method: "GET" },
		options,
	);
};

export type GetAuthValidateResult = NonNullable<
	Awaited<ReturnType<typeof getAuthValidate>>
>;
export type PostAuthSignOutResult = NonNullable<
	Awaited<ReturnType<typeof postAuthSignOut>>
>;
export type PostAuthSignUpResult = NonNullable<
	Awaited<ReturnType<typeof postAuthSignUp>>
>;
export type PostAuthSignInResult = NonNullable<
	Awaited<ReturnType<typeof postAuthSignIn>>
>;
export type GetIndexResult = NonNullable<Awaited<ReturnType<typeof getIndex>>>;
